services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fiber_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
