// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/bps-kota-bontang/fiber-starter/app"
	"github.com/bps-kota-bontang/fiber-starter/config"
	"github.com/bps-kota-bontang/fiber-starter/database"
	"github.com/bps-kota-bontang/fiber-starter/handlers"
	"github.com/bps-kota-bontang/fiber-starter/repositories"
	"github.com/bps-kota-bontang/fiber-starter/services"
	"github.com/bps-kota-bontang/fiber-starter/validator"
	"github.com/gofiber/fiber/v2"
)

// Injectors from wire.go:

// Initialize App
func InitializeApp() (*fiber.App, error) {
	configDatabase := config.LoadConfigDatabase()
	db, err := database.ConnectDB(configDatabase)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	validate := validator.ProvideValidator()
	userHandler := handlers.NewUserHandler(userService, validate)
	fiberApp := app.NewFiberApp(userHandler)
	return fiberApp, nil
}
