// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/bps-kota-bontang/fiber-starter/app"
	"github.com/bps-kota-bontang/fiber-starter/config"
	"github.com/bps-kota-bontang/fiber-starter/database"
	"github.com/bps-kota-bontang/fiber-starter/handlers"
	"github.com/bps-kota-bontang/fiber-starter/repositories"
	"github.com/bps-kota-bontang/fiber-starter/services"
	"github.com/bps-kota-bontang/fiber-starter/validator"
)

// Injectors from wire.go:

// Initialize App
func InitializeApp() (*AppContainer, error) {
	appConfig := config.LoadAppConfig()
	databaseConfig := config.LoadDatabaseConfig()
	db, err := database.ConnectDB(databaseConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	validate := validator.ProvideValidator()
	userHandler := handlers.NewUserHandler(userService, validate)
	fiberApp := app.NewFiberApp(appConfig, userHandler)
	appContainer := &AppContainer{
		App:    fiberApp,
		Config: appConfig,
	}
	return appContainer, nil
}
